### ISSUE TITLE
🐞 Text selection is janky while dragging across lines

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#10]
### Description

While making a multi-line text selection, it can appear janky because the background shifts briefly while dragging across lines.

### To Reproduce

1. Make a multi-line selection.
2. Notice that while dragging across lines the selection background sometimes shifts.

### Expected Behavior

The selection background should remain in the same place while dragging across lines.

### Version Information

CodeEditTextView: 0.7.0
macOS: 14.0
Xcode: 15.0

### Screenshots

CodeEdit

https://github.com/CodeEditApp/CodeEditTextView/assets/806104/78628221-5620-4339-9edc-41d887093e5f

CodeEdit (frame-by-frame tracking)

https://github.com/CodeEditApp/CodeEditTextView/assets/806104/515e5113-1010-4a12-9423-43ecf6d1ade7

Xcode

https://github.com/CodeEditApp/CodeEditTextView/assets/806104/7a092bfb-b279-4558-8556-c18a990cc8e4

**Comment by thecoolwinter** [comment]
I can't seem to reproduce this, there's been a few changes to selection drawing and a bunch of bug fixes since this was created. Is this still an issue?
