### ISSUE TITLE
🐞 Cursor remains arrow when over editor

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#107]
### Description

Cursor remains an arrow when hovering over editor.

### To Reproduce

Hover over the editor.

### Expected behavior

When hovering over editor, cursor should change to an I-beam to indicate editable text.

**Comment by austincondiff** [comment]
I am noticing this in more apps than CodeEdit. I am starting to think it is a macOS bug. Can anyone confirm?

**Comment by ben-p-commits** [comment]
Confirmed in a handful of web browsers in various html fields and the URL
bar...

**Comment by austincondiff** [comment]
I've had to restart my machine to fix this. I'd like to report this bug to Apple but I have no idea what causes it and how to fix it other than restarting. Closing for now.
