### ISSUE TITLE
🐞 When changing font size, line heights are not recalculated until view refresh

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#110]
If you change your font size, lines do not grow with the new size as expected. The lines only reflect the font size change when changing tabs or closing and reopening the file.

**Comment by ben-p-commits** [comment]
@austincondiff - can we generalize this issue to instead be:

**Changing any code editing preference should automatically update the CodeEditTextView with the changes**

**Comment by thecoolwinter** [comment]
Closed with #122
