### ISSUE TITLE
✨ Command+Backspace Keyboard Shortcut to delete whole line

### ISSUE THREAD

**Issue by MrDevel0per** [CodeEditApp/CodeEditTextView#118]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

In Xcode, one of the default keyboard shortcuts is <kbd>⌘</kbd><kbd>⌫</kbd>, which deletes to the start of the line. This is used across several text editors and should be implimented in CodeEdit. This allows the user to delete an entire line of code to the start instead of having to either select the line or keep holding the backspace key.

### Describe alternatives you've considered

I think this is the simplest solution and has the standard shortcut, although the shortcut could be changed to accommodate CodeEdit's other features. I think that the only other options would be either continuing to hold the delete key or some sort of "delete" icon next to the line in the `CodeEditTextView`. 

### Additional context

Here is a video in Xcode of what I am suggesting:

https://user-images.githubusercontent.com/104732280/212492621-d3f9e23f-9cec-4868-a984-9fcf12461da4.mov

In this video, I use the <kbd>⌘</kbd><kbd>⌫</kbd> shortcut to delete the entire line, which makes editing code much easier.

**Comment by austincondiff** [comment]
One important thing to take note of, is it deletes all text on the line leading up to the cursors position and retains all text after it. As shown in the above video, if the cursor is placed at the end of the line, it will get rid of the entire line.

**Comment by luah5** [comment]
@austincondiff I think this can be closed as it already works:

https://user-images.githubusercontent.com/128280019/230992033-6338f619-34f0-402d-ab26-2b3a686f7f9b.mov
