### ISSUE TITLE
🐞 Unexpected horizontal scrolling

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#148]
### Description

There is no horizontal overflow yet I can scroll horizontally. It seems the amount of horizontal scroll is the same as the width of the ruler view.

### To Reproduce

1. Open a file
2. Scroll horizontally

### Expected behavior

Scrolling horizontally is only possible when content overflows with of viewport.

### Additional context

This bug may have been introduced with #141.

### Screenshots

https://user-images.githubusercontent.com/806104/220971742-4660ea93-fd39-4376-b0d4-210a1d67e549.mp4

**Comment by thecoolwinter** [comment]
Closed with #177
