### ISSUE TITLE
🐞 Text gets misaligned as it is typed

### ISSUE THREAD

**Issue by ryohajika** [CodeEditApp/CodeEditTextView#151]
### Description

Thank you so much for all of your hard works! This project is amazing...
Here are few things I found from the latest alpha release in basic text editing.

1) Vertical text alignment is off somehow
<img width="153" alt="Screenshot 2023-02-27 at 12 28 22 PM" src="https://user-images.githubusercontent.com/4526634/221443906-9eb9d6f7-8d1a-4af9-abaf-988d5adb0f01.png">

2) At the beginning of text edit, no colorization of text (in my case, `.swift` file) until 10th line did happen
3) When the file you're editing is short and blank spaces are there at the bottom of the file, you cannot click there to move the edit cursor to the most bottom line

I hope this report helps future improvement...

Environment: MBP 14-inch, 2021, M1P, Ventura 13.2.1

### To Reproduce

make a new text file, open it in CodeEdit, start edit it then you would see all three.

### Expected behavior

1) It should be aligned vertically.
2) Live interpreter(?) should detect the file format and highlight keywords in the editor
3) Should be able to click the empty part of the file on editor to make the text editor cursor jump to the bottom line

### Version information

CodeEdit: [Version 0.0.2-alpha (27)]
macOS: [13.2.1]
Xcode: [14.2]

### Related issues
- #152
- #20

**Comment by lukepistrol** [comment]
@ryohajika can you confirm this is still happening on the latest release?

**Comment by ryohajika** [comment]
@lukepistrol @luah5 now this error is gone I guess! Thanks so much for your effort:)

(now there's another error with the CodeTextEditApp `0.0.3-alpha.32` release that you get your text glitched and destroyed when you edit some text and do undoing. I may setup another error report on the repo for the app.)

**Comment by luah5** [comment]
Glad to know that this is fixed @ryohajika!
