### ISSUE TITLE
🐞 Padding on Line 1 & 2 is missing when no characters are found

### ISSUE THREAD

**Issue by tdeverx** [CodeEditApp/CodeEditTextView#152]
### Description

See video below:

https://user-images.githubusercontent.com/44447832/218308866-44375803-14c9-4f3c-b58f-dbba7a5d5d36.mov

### To Reproduce

1. Create New File,
2. Start Typing,
3. See Issue.

### Expected behavior

Padding should be applied even when the line is empty.

### Version information

CodeEdit: 0.0.1-alpha (25)
macOS: 13.1 (22C65)
Xcode: 14.2 (14C18)

### Related issues
- #20
- #151

**Comment by TheAbstractDev** [comment]
Hey ! I'd like to do this task

**Comment by FastestMolasses** [comment]
This looks like an issue in the STTextView package. I've been looking at related issues around the text view, seems most of them are coming from this library. #1379 #1385 #184 #1008

**Comment by thecoolwinter** [comment]
Fixed with #211.
