### ISSUE TITLE
✨ Scale line numbers relative to font size

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#157]
### Description

The line numbers in the ruler should scale relative to the editor font size as it increases or decreases. The line number font size is smaller than the editor font so it should scale proportionally.

### Screenshots

https://user-images.githubusercontent.com/806104/223864722-9276941a-22bc-4b62-b013-15ffaacc69d9.mp4

This is Xcode, we should be handling this similarly.

**Comment by Eliulm** [comment]
@austincondiff You can assign this to me since I have already got it pretty much done. Only need to tweak the scaling a bit.

**Comment by luah5** [comment]
how is this going @Eliulm? this is definitely a must-have ever since https://github.com/CodeEditApp/CodeEdit/pull/1191 was merged.
