### ISSUE TITLE
🐞Horizontal scrolling with rubberbanding

### ISSUE THREAD

**Issue by matthijseikelenboom** [CodeEditApp/CodeEditTextView#158]
### Description

It's currently possible to scroll horizontally in the TextView. That's fine, VSCode also does this. Xcode, however, does not. 

Currently, when all of the files content is in view, it's still possible to scroll horizontally, with rubberband effect. This isn't desired.

If we want to follow Xcode specifically, then horizontal scrolling should be removed and text should be wrapped when it doesn't fit on screen. But I like the idea to put this as a setting more, where the user can choose to use the VSCode or Xcode style.

### To Reproduce

1. Open a file
2. Scroll horizontally.

### Expected behavior

N/A

### Version information

CodeEditTextView: [0.0.3-alpha 29]
macOS: [13.2.1]
Xcode: [14.2]

**Comment by austincondiff** [comment]
This is controlled with this setting under Text Editing...

<img width="323" alt="image" src="https://user-images.githubusercontent.com/806104/224164290-db5e65ed-4dd1-40ef-88e3-612a716d505b.png">

That said, when it is changed, the editor does not respond. To see the changes take effect, the user must close and reopen the file. This needs to be fixed to reflect changes immediately after the user clicks the checkbox.

**Comment by matthijseikelenboom** [comment]
Oh didn't know that was a setting already. Should be default enabled if you ask me. It's also possible to always scroll to the right, even if everything is in view/on screen.

**Comment by austincondiff** [comment]
@matthijseikelenboom that scrolling is most likely caused by #148.
