### ISSUE TITLE
🐞 Erratic behavior of interline spacing

### ISSUE THREAD

**Issue by richardtop** [CodeEditApp/CodeEditTextView#168]
### Description

Interline spacing behavior is inconsistent and erratic, line spacing is not respected after resizing a window. Often, a new line inserted is displayed as having a larger interline spacing compared to the one that is required.

### To Reproduce

1. Create a file with some text, e.g.:

> CalendarKit is a Swift calendar UI library for iOS and Mac Catalyst. It looks similar to the Apple Calendar app out-of-the-box, while allowing customization when needed. CalendarKit is composed of multiple modules which can be used together or independently.

(on a single line, no newline characters)

2. Press "return" key and observe the interline spacing
3. Type some text, e.g. "L"
4. Observe that the interline spacing has increased
5. Type "return" a few more times, type some text after either each line or at some point down...
6. Observe the interline spacing, remember it's size
7. Try to resize the window by dragging it's bottom right corner
8. Observe that the interline spacing collapses to the correct size now and the text looks consistent

### Expected Behavior

Interline spacing is consistent across the whole file, both, the new (added) lines and the old lines have the same interline spacing.

### Version Information

CodeEdit: 0.0.3-alpha.30

### Screenshots

<img width="842" alt="Bildschirm­foto 2023-03-19 um 05 45 19" src="https://user-images.githubusercontent.com/8013017/226153111-3f45533e-aa68-434f-b302-314f2758a427.png">
<img width="842" alt="Bildschirm­foto 2023-03-19 um 05 45 25" src="https://user-images.githubusercontent.com/8013017/226153113-829a98d8-c524-41ca-8f56-2b8e2e27866a.png">
<img width="530" alt="Bildschirm­foto 2023-03-19 um 05 58 58" src="https://user-images.githubusercontent.com/8013017/226153117-f7aa742d-f40a-43ff-8776-26fd490f172d.png">
<img width="495" alt="Bildschirm­foto 2023-03-19 um 05 59 09" src="https://user-images.githubusercontent.com/8013017/226153119-8f88d7f5-f4db-437b-abeb-c6c2f3003c34.png">

**Comment by thecoolwinter** [comment]
Looks like it's maybe related to #142. Is this still reproducible in the latest CodeEdit alpha?

**Comment by thecoolwinter** [comment]
Closing this issue due to no response, likely fixed with #142 but feel free to re-open if not the case.
