### ISSUE TITLE
🐞 Line number briefly flashes in after changing appearance when clicking a line

### ISSUE THREAD

**Issue by luah5** [CodeEditApp/CodeEditTextView#176]
### Description

In the opposite of the system theme, when clicking on a line the line number flashes for a split second for some reason this only happens when the theme is opposite of the system theme.

### To Reproduce

1. Set your theme to dark mode
2. Open or create a file with 2 lines or more
3. click on the line number's text and notice that it flashes

### Expected Behavior

I would expect the line number to stay a solid color, not to change color like in Xcode and VS Code

### Version Information

CodeEdit: [0.0.3-alpha.32]
CodeEditTextView: [0.6.1]
macOS: [13.2.1]

### Screenshots

https://user-images.githubusercontent.com/128280019/232200794-6b46f4fa-96d9-4317-a1f9-3110e6c6b0c8.mov

**Comment by luah5** [comment]
You're completely right! I'll edit the issue accordingly.

**Comment by thecoolwinter** [comment]
This was fixed in 2921e93d by @austincondiff.
