### ISSUE TITLE
🐞 Line text overlaps

### ISSUE THREAD

**Issue by luah5** [CodeEditApp/CodeEditTextView#183]
### Description

When changing the font size from CE using Command + or just changing the font size in the settings the line numbers overlap

### To Reproduce

1. Open a workspace (or standalone file)
2. Increase the font size using Command + or changing the font size in CodeEdit settings
3. Notice the lines overlap

### Expected Behavior

The line numbers should not overlap

### Version Information

CodeEditTextView: [0.6.1]
macOS: [13.2.1]
Xcode: [14.3]

### Additional Context

Similar to #152 and #20

### Screenshots

https://user-images.githubusercontent.com/128280019/235316524-4e2f7d0e-7ffc-41d2-a3e6-74105b81e22b.mov

**Comment by thecoolwinter** [comment]
Fixed in #211. However there is a font resizing bug, so closing in favor of #219.
