### ISSUE TITLE
🐞 Last line touching the editor view's edge is invisible

### ISSUE THREAD

**Issue by wannafedor4** [CodeEditApp/CodeEditTextView#19]
### Description

When your code excedes

### To Reproduce

1.  Open a file that has enough code to fill the editor
2. Observe

### Expected Behavior

The line should be visible.

### Version Information

CodeEdit: 0.0.3-alpha (37)
macOS: 14.3 Beta (23D5033f)
Xcode: 15.2 beta (15C5500c)

### Screenshots

https://github.com/CodeEditApp/CodeEdit/assets/151413500/b3031de4-f8c5-4a99-a5c0-d10c0cb8b504

![About the Mac](https://github.com/CodeEditApp/CodeEdit/assets/151413500/ad1077c4-8f86-45b5-9955-637bfe36f1bf)

**Comment by thecoolwinter** [comment]
@wannafedor4 you're absolutely right this is probably an issue with CETV, I managed to miss this issue before could you tell me if it's still a problem now?

**Comment by wannafedor4** [comment]
@thecoolwinter no, it seems solved.

**Comment by wannafedor4** [comment]
Okay I guess it still is an issue. It looks like something might be blocking the last line.
