### ISSUE TITLE
🐞 Text scrolls underneath ruler

### ISSUE THREAD

**Issue by wjk** [CodeEditApp/CodeEditTextView#195]
### Description

Apparently, CodeEditTextView does not fully take into account the size of the left-hand ruler when positioning its content. As a result, when I open a file in CodeEdit, the left-hand side of each line is cut off because it is being drawn underneath the ruler. I can scroll to the right to pull the content out from underneath the ruler, but this cuts off the part of the line at the right side of the screen. This is terribly annoying and makes line-wrap not work properly.

### To Reproduce

1. Open a file in CodeEdit
2. Observe the cut off text and horizontal scrollbar

### Expected Behavior

The text in the text view should appear to the right of the ruler, not under it. There should be no horizontal scrollbar.

### Version Information

CodeEdit: 0.0.3-alpha (32)
macOS: 13.4 (22F66)
Xcode: 15.0 (15A5160n)

### Additional Context

Previously reported as https://github.com/CodeEditApp/CodeEdit/issues/1306.

### Screenshots

<img width="883" alt="Screenshot 2023-06-09 at 9 01 14 PM" src="https://github.com/CodeEditApp/CodeEditTextView/assets/1915951/fbd83926-88a3-4790-af3c-50f37f0c3131">
<img width="878" alt="Screenshot 2023-06-09 at 9 01 00 PM" src="https://github.com/CodeEditApp/CodeEditTextView/assets/1915951/a9964185-52dc-4543-8c68-f7572b6c29e0">

**Comment by luah5** [comment]
I'm pretty sure this was fixed in #177, are you running CodeEdit from Xcode or from the latest app release on github?

**Comment by wjk** [comment]
Latest release on GitHub. I tried to build from source first, but Xcode kept choking on the 70MB xcframework in CodeEditLanguages. It generally just quit downloading entirely, and I know of no good way to get it to resume without deleting the clones and starting over — at which point Xcode usually chokes again. If you have any ideas as to how I could address this, I’m all ears.

**Comment by wjk** [comment]
Strike that regarding the download errors. I have just got it to work.

**Comment by thecoolwinter** [comment]
This should be fixed with #211. The gutter has been reimplemented to be a floating view instead of a ruler view and the text view updated to account for that automatically.
