### ISSUE TITLE
🐞 Unexpected Undo behavior

### ISSUE THREAD

**Issue by ryohajika** [CodeEditApp/CodeEditTextView#203]
### Description

When you edit text and undo changes you made, the undo(s) would be realized at some point but doesn't recover previous state and has some glitches in the text you didn't edit.

### To Reproduce

1. Open a file (`.swift` file in this case, and I realized the app doesn't support opening `.xcodeproj` file, which is not the point here though).
2. Edit few lines like:
<img width="395" alt="Screenshot 2023-04-15 at 7 14 31 PM" src="https://user-images.githubusercontent.com/4526634/232194749-b3c875c1-d0d4-4352-ba49-76d1fcbdad9d.png">
3. Perform `Cmd+Z` multiple times
4. You get something like this:
<img width="426" alt="Screenshot 2023-04-15 at 7 14 52 PM" src="https://user-images.githubusercontent.com/4526634/232194800-836371a8-d08e-4594-8e81-f39598f46cb6.png">

### Expected Behavior

Bring back the previous state as it was originally.

### Version Information

CodeEdit: 0.0.3-alpha-32
macOS: 13.3.1 (MBP "14 2021)
Xcode: 14.3 *(I did install the app **from the released installer, not from source**)*

**Comment by thecoolwinter** [comment]
I've got a fix for this ready. Waiting for a PR on STTextView to merge and this'll be fixed 👍
