### ISSUE TITLE
🐞 Highlighting takes a while

### ISSUE THREAD

**Issue by 0xWDG** [CodeEditApp/CodeEditTextView#21]
# Highlighting
After opening a file highlighting doesn't start
<img width="1112" alt="Screenshot 2022-06-11 at 15 43 40" src="https://user-images.githubusercontent.com/1290461/173190475-31e3c97c-79e8-4e02-acdc-4c1d309365df.png">

After pressing enter (last line) it starts highlighting
<img width="1112" alt="Screenshot 2022-06-11 at 15 43 17" src="https://user-images.githubusercontent.com/1290461/173190483-61108879-3d00-4ab0-b171-f83b189cee39.png">

**Comment by lukepistrol** [comment]
This just happens when opening a `*.swift` file right?

**Comment by austincondiff** [comment]
We might need to show "Loading X language features" this in the CodeEdit activity bar while this completes. We'd need to somehow pull that state out of this view.

**Comment by lukepistrol** [comment]
@thecoolwinter is this fixed with #59 ?

**Comment by thecoolwinter** [comment]
Yes, closed with incremental highlighting #59. CodeEdit will now only try to highlight the visible text which greatly improves the initial highlight time
