### ISSUE TITLE
How to choose only JSON methods when import this repo?

### ISSUE THREAD

**Issue by Jinxiansen** [CodeEditApp/CodeEditTextView#25]
When I tried to use CodeEditTetView on macOS, and only used to parse **JSON**, I found that it depends on many parsing libraries in other languages, is there a way to remove other libraries according to personal needs?

Because I only need methods related to json parsing.

![image](https://user-images.githubusercontent.com/16829428/173238473-8d968091-235c-4be2-8f34-b1ffd54d4aa6.png)

Thanks!

**Comment by lukepistrol** [comment]
They get all bundled at build-time. Once you run the app only parsers for languages you actually have opened get instantiated (lazy-loaded).

**Comment by Jinxiansen** [comment]
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/16829428/173346747-d95ada25-a0f2-48a9-9847-b297709acd1a.png">
Thanks for your response!
When I import this repo, I got some errors.

**Comment by lukepistrol** [comment]
Fix incoming! `STTextView` implemented some non-backwards compatible features on Swift 5.7.

**Comment by Jinxiansen** [comment]
Got it, I need upgrade to Swift 5.7 version and try to it.
Thanks so much!

**Comment by Jinxiansen** [comment]
Okay, thanks!
