### ISSUE TITLE
🐞 Input not cleared when using Chinese input method

### ISSUE THREAD

**Issue by zhangle** [CodeEditApp/CodeEditTextView#26]
### Description

When using Chinese input method, chineses and original pinyin characters remains  both.

### To Reproduce

Using Chinese input method or other else

### Expected Behavior

Only chineses remains

### Version Information

CodeEditTextView: [0.7.3]
macOS: [14.3.1]
Xcode: [15.0.1]

### Screenshots

<img width="821" alt="image" src="https://github.com/CodeEditApp/CodeEditTextView/assets/1232613/35232ed6-176d-43ae-9f36-8eae8426646a">

https://github.com/CodeEditApp/CodeEditTextView/assets/1232613/a82ae8c2-6e80-453a-af4b-e6ef74b60b33

**Comment by thecoolwinter** [comment]
This looks related to @austincondiff's issue mentioned here:

https://canary.discord.com/channels/951544472238444645/987416899816149024/1202757132852797510

Looking into this.
