### ISSUE TITLE
✨ Incremental Syntax Highlighting

### ISSUE THREAD

**Issue by lukepistrol** [CodeEditApp/CodeEditTextView#27]
At the moment each keystroke triggers highlighting for the whole document. While this is not an issue for small documents this might bring big performance losses on larger documents.

Though there needs to be some kind of *padding* of the changed text range since a single character cannot be parsed to anything. Ideally this would be the entire current line.

## Ideally:

- [ ] only highlight *current* scope.

## Alternatively:

- [ ] Highlight only current line on text input.
  **When this results in an error there should be two options:**
    - [ ] When no further editing is done (i.e. some small timeout), try highlighting the whole document.
    - [ ] When further editing is done, do nothing.
- [ ] When selected text (multi-line) is deleted, also include previous and following line.
- [ ] When multi-line text is inserted highlight those lines.

**Comment by austincondiff** [comment]
From what I understood, a key advantage tree sitter provides is highlighting in the scope of the change, not necessarily the current line itself. Is this something we could instead do?
