### ISSUE TITLE
✨ Current Line Highlight

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#34]
Current line needs to be highlighted and current line number is primary text color.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/806104/159621955-17360f30-3cff-4e69-ad34-b0ced513b593.png">

**Comment by NakaokaRei** [comment]
@austincondiff 
I want to work on this issue!
Can you please assign it to me?

**Comment by austincondiff** [comment]
Sure thing! One thing to note, the top line is highlighted in this screenshot, so it is working however there are two things that need to happen here. 
1. The highlight needs to extend into the gutter.
2. The line number needs to be more prominent.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/806104/193626963-01d9e895-8db8-45f7-8748-607d3cc27fb2.png">

**Comment by NakaokaRei** [comment]
@austincondiff 
Thank you for the advice!
I will investigate and report back if I have to change STTextView 🙇

**Comment by NakaokaRei** [comment]
@austincondiff 
As far as you can tell, as you are talking about, it doesn't look like I can tackle this issue without changing STTextView.
This is difficult for me and I have no prospects for development, so I will remove the assign for now.
Sorry 🙇

I think this CodeEdit is a great project and I'll comment as soon as I find an issue I can do myself!

**Comment by Eliulm** [comment]
I am currently finalizing my pull request for the STTextView repository. With that, we can add line highlighting, just like in Xcode.

**Comment by austincondiff** [comment]
Closing this as the line highlight has been implemented.
