### ISSUE TITLE
✨ Page Up and Page Down Keyboard Navigation

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#4]
### Description

Users should be able to navigate the text view by pressing page up and page down on their keyboard.

Originally planned for CodeEditApp/CodeEditSourceEditor#211 but was cut to reduce PR complexity.

@thecoolwinter feel free to edit to provide additional details.

**Comment by thecoolwinter** [comment]
This should have been closed with #38
