### ISSUE TITLE
🐞 Text changes from bold to not bold when typing

### ISSUE THREAD

**Issue by KaiTheRedNinja** [CodeEditApp/CodeEditTextView#45]
https://user-images.githubusercontent.com/88234730/177717085-9b40d21b-b6b4-4365-a423-a3c3437905b3.mov

When typing in a file (doesn't matter what the file extension is, so long as CodeEdit can syntax highlight it), the text changes from bold to non-bold, and/or the font size changes.

**Comment by lukepistrol** [comment]
@thecoolwinter is this fixed with #59 ?

**Comment by thecoolwinter** [comment]
Yes it is

**Comment by thecoolwinter** [comment]
Closed with #59
