### ISSUE TITLE
🐞 Text was accidentally hidden when the Enter key was pressed

### ISSUE THREAD

**Issue by RonghuaHe** [CodeEditApp/CodeEditTextView#48]
### Description

When switching the input method to Chinese or Japanese and typing part of the text, press the Enter button a few times, the text is accidentally hidden

https://github.com/user-attachments/assets/d97e53ce-ec60-4977-9ab0-27b714726943

### To Reproduce

1. When switching the input method to Chinese or Japanese 
2. and typing part of the text, 
3. press the Enter button a few times, 
4. the text is accidentally hidden

### Expected Behavior

Fixed text being hidden by accident

### Version Information

CodeEdit: [e.g. 0.2.x-alpha.y]
macOS: [e.g. 15.4]
Xcode: [e.g. 14.2]

**Comment by thecoolwinter** [comment]
This should be fixed with the linked PR, I'm going to close this but please re-open it if the issue persists.
