### ISSUE TITLE
✨ Font Ligatures

### ISSUE THREAD

**Issue by AngelTheTwin** [CodeEditApp/CodeEditTextView#50]
### Is your feature request related to a problem? Please describe.

Nope.

### Describe the solution you'd like

Using a custom font doesn’t apply the font ligatures. I think it would be nice for all those who use custom fonts to make the editor more personal. 

### Describe alternatives you've considered

I tried adding a font I really like called Fira Code but it won't apply the ligatures.

### Additional context

![image](https://user-images.githubusercontent.com/62160767/184461447-dfe3381b-94cd-45aa-a7b1-ac11d7577ee6.png)

**Comment by thecoolwinter** [comment]
This has been supported for a while, closing this issue.
