### ISSUE TITLE
Swift package needs updating

### ISSUE THREAD

**Issue by mattmassicotte** [CodeEditApp/CodeEditTextView#51]
Hello!

The maintainer of the Swift tree-sitter parser has just merged in SPM support. I'd like to remove my personal branch, but wanted to let you know first before I do that. Unlike some other parsers, the branch `with-generated-files` is still required.

https://github.com/alex-pinkus/tree-sitter-swift/tree/with-generated-files

**Comment by lukepistrol** [comment]
So basically we need to use the `with-generated-files` branch instead of `master`?

**Comment by mattmassicotte** [comment]
You got it - thanks for taking care of this!
