### ISSUE TITLE
🐞 Font doesn't apply consistently

### ISSUE THREAD

**Issue by alicerunsonfedora** [CodeEditApp/CodeEditTextView#55]
### Description

When using a custom font, the editor appears to only apply that font to select areas when the file has syntax highlighting.

### To Reproduce

1. Open CodeEdit Settings > Text Editing.
2. Change the font to anything other than the default.
3. Open a file in CodeEdit.
4. Notice the inconsistent font application.

### Expected behavior

The same font should be used throughout the entire editor view, regardless of syntax highlighting.

### Version information

CodeEdit: 1.0
Hash: (Commit) 095abfec2475ca053bb7783572e4ae9a38d514ea
MacOS: 13.0 beta 4 (22A5311f)
Xcode: 14.0 beta 4 (14A5284g)

### Additional context

This is an example screenshot demoing the behavior. I've set my font to Fira Code Retina (size 13). Notice that, here, the identifier "Foundation" uses the correct font, as well as the line gutter, whereas everything else doesn't.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/13445064/183081013-f13cae59-7a3b-4a96-a21e-27f9eb61b512.png">

**Comment by lukepistrol** [comment]
@thecoolwinter is this fixed with #59 ?

**Comment by thecoolwinter** [comment]
Yes, closed with #59
