### ISSUE TITLE
🐞 Key event should be released if text view lost focus or after relinquished first responder

### ISSUE THREAD

**Issue by neesonqk** [CodeEditApp/CodeEditTextView#57]
https://github.com/CodeEditApp/CodeEditTextView/blob/9b300d8a37589f4e16719f98d1bf8763940ef0b2/Sources/CodeEditTextView/STTextViewController.swift#L182

Here, this line will be always executed whenever 'Tab' key is pressed, e.g. if the focus is on a other tab or command palette, all open tabs will insert a tab space.

``` swift

textView?.insertText(String(repeating: " ", count: tabWidth))

```

**Comment by thecoolwinter** [comment]
Good catch. This should be triggered in the delegate method `textView(_ textView: STTextView, didChangeTextIn affectedCharRange: NSTextRange, replacementString: String)`.

**Comment by austincondiff** [comment]
Can we confirm that this issue still exists?
