### ISSUE TITLE
🐞 Line number font is incorrect

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#58]
The line number font does not align with Xcode.

<img width="213" alt="image" src="https://user-images.githubusercontent.com/806104/190232689-c70ca796-8583-4279-b574-513e1b3d8fc5.png">

Left: Xcode | Right: CodeEdit

The font needs to be sans-serif, narrower, with the color less prominent.

**Comment by lukepistrol** [comment]
Just want to leave this here. Did some research a while back and this might help:

```swift
private var lineGutterFont: NSFont {
    let fontSize: Double = 10

    // TODO: calculate the font size depending on the editors font size.
    let font = NSFont.monospacedSystemFont(ofSize: fontSize, weight: .medium)

    let alt0NoSlash: [NSFontDescriptor.FeatureKey: Int] = [
        .selectorIdentifier: 6,
        .typeIdentifier: kStylisticAlternativesType,
    ]

    let alt1NoSerif: [NSFontDescriptor.FeatureKey: Int] = [
        .selectorIdentifier: 8,
        .typeIdentifier: kStylisticAlternativesType,
    ]

    let descriptor = font.fontDescriptor.addingAttributes([.featureSettings: [alt0NoSlash, alt1NoSerif]])

    return NSFont(descriptor: descriptor, size: 0) ?? font
}
```

**Comment by austincondiff** [comment]
That gets me the alternate characters like the open 4 however I still need to be able to reduce the width and tracking. Any idea how I might do that?

**Comment by lukepistrol** [comment]
> That gets me the alternate characters like the open 4 however I still need to be able to reduce the width and tracking. Any idea how I might do that?

Maybe something [here](https://developer.apple.com/documentation/appkit/nsfont/advanced_font_metrics)

**Comment by ben-p-commits** [comment]
@austincondiff, @lukepistrol - I believe the font you're looking for is actually sneakily bundled into Xcode.

take a look in: `/Applications/Xcode.app/Contents/SharedFrameworks/DVTUserInterfaceKit.framework/Versions/A/Resources/Fonts`

and say hello to this little guy:
**XcodeDigits-regular.ttf**

<img width="610" alt="image" src="https://user-images.githubusercontent.com/5067237/210666611-0563b903-25fe-4730-b899-c968dac9105d.png">

I would guess that it's proprietary.

**Comment by austincondiff** [comment]
I have thought about sneaking it in, but probably not. I think we can get a look like this with the SF variable font (not sure if we can use it now or if we need to wait).

**Comment by ben-p-commits** [comment]
Looks like variable fonts are only available in OS 13+...

https://developer.apple.com/documentation/appkit/nsfont/width?changes=latest_3_5_2

**Comment by austincondiff** [comment]
We will be using ExtensionKit and the new form style in Settings. The though it once we are out of beta, 13 will be standard by that point. So I'd say let's try to achieve the same look with variable fonts!

**Comment by austincondiff** [comment]
@ben-p-commits we will be increasing our minimum target to macOS 13 if you wanted to take a stab at doing this via variable fonts.

**Comment by ben-p-commits** [comment]
I just updated to ventura- happy to dive back in!

**Comment by austincondiff** [comment]
Perfect, I am assigning this to you.

**Comment by austincondiff** [comment]
@Eliulm would you like to try to include this in your PR (#163) or should we tackle this later?

**Comment by Eliulm** [comment]
@austincondiff Yeah, I will see what I can do.

**Comment by austincondiff** [comment]
@Eliulm it looks like #163 was merged. Feel free to open a separate PR.

**Comment by Eliulm** [comment]
So I looked into it and found that apple only ships the `SF Pro` font as a variable font. This means that it is the only font where I can adjust the glyph width, as far as I know. However, the problem with that font is, that It does not have the open four:
<img width="82" alt="image" src="https://user-images.githubusercontent.com/82230675/226107661-26a72d7d-0234-4bca-89bc-8817747b15ef.png">
The `SF Mono` font has the open four, but the problem there is, as you pointed out before, that the glyphs are a bit wider than the Xcode digits font:
<img width="82" alt="Screenshot 2023-03-18 at 13 58 49" src="https://user-images.githubusercontent.com/82230675/226107799-0b7daf72-6c1c-4a42-844e-5326f702f7e7.png">
<img width="82" alt="Screenshot 2023-03-18 at 14 01 25" src="https://user-images.githubusercontent.com/82230675/226107912-7bd02ae7-d5c0-458f-b3fb-da39f64ac735.png">
As of now, I do not know, how I could change that :/

**Comment by austincondiff** [comment]
The open 4 is an alternate character. 

https://user-images.githubusercontent.com/806104/226121452-2343071c-6d4d-404a-98e4-503d90433699.mov

I forget how, but there is a way to do this in Swift.

**Comment by Eliulm** [comment]
I have found the stylistic set, that uses the open four. However, it also uses zero with a slash. I have tried all other stylistic sets, but none have the zero with a slash and the open four at the same time. This is how it currently looks like now:
(Xcode left, CE right)
<img width="96" alt="ruler_comparison" src="https://user-images.githubusercontent.com/82230675/226741964-e19ad6ba-bbf4-449c-90f7-263e34f88412.png">
I also made the ruler font size dependent on the text font size:
```swift
var rulerFont: NSFont {
        let fontSize: Double = (font.pointSize - 1) + 0.7 // 11.7 @ 12font and 1,7 lineheight
        let fontAdvance: Double = font.pointSize * 0.49 + 0.6
        let fontWeight = NSFont.Weight(rawValue: 0.0005)
        let fontWidth = NSFont.Width(rawValue: -0.13)

        let font = NSFont.systemFont(ofSize: fontSize, weight: fontWeight, width: fontWidth)

        /// Set the 4 to open four and alter the shape of 6 and 9
        let alt469: [NSFontDescriptor.FeatureKey: Int] = [
            .selectorIdentifier: 12,
            .typeIdentifier: kStylisticAlternativesType
        ]

        /// Make all digits monospaced
        let monoSpaceDigits: [NSFontDescriptor.FeatureKey: Int] = [
            .selectorIdentifier: 0,
            .typeIdentifier: kNumberSpacingType
        ]

        let features = [alt469, monoSpaceDigits]
        let descriptor = font.fontDescriptor.addingAttributes([.featureSettings: features, .fixedAdvance: fontAdvance])
        return NSFont(descriptor: descriptor, size: 0) ?? font
    }
```

**Comment by thecoolwinter** [comment]
@Eliulm It looks like your alt469 is enabling the high legibility setting (`kStylisticAltSixOnSelector` = 12) which enables the slashed 0. You'll have to add the alt 4 and alt 6 and 9 separately using their respective keys:
```swift
let alt4: [NSFontDescriptor.FeatureKey: Int] = [
    .selectorIdentifier: kStylisticAltOneOnSelector,
    .typeIdentifier: kStylisticAlternativesType
]

let alt6and9: [NSFontDescriptor.FeatureKey: Int] = [
    .selectorIdentifier: kStylisticAltTwoOnSelector,
    .typeIdentifier: kStylisticAlternativesType
]
```
Left: Xcode, Right: CE
<img width="58" alt="Screenshot 2023-03-22 at 1 26 50 PM" src="https://user-images.githubusercontent.com/35942988/227002173-0127879b-f76b-45d0-90c2-d15623b90d08.png">

**Comment by austincondiff** [comment]
@Eliulm how are we looking with this?

**Comment by Eliulm** [comment]
Done, going to create a PR soon
