### ISSUE TITLE
✨ Customize Fonts, Spacing, Line Height

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#62]
### Description

Add the ability to customize fonts, letter spacing, and line height.

### Completion

- [x] Font customization
- [x] Letter spacing
- [x] Line height

**Comment by ahmdyasser** [comment]
Hi @austincondiff, you mean creating something like this? 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/42544598/198840333-e30cab78-f184-4f28-9d75-6cd57e73e252.png">

**Comment by austincondiff** [comment]
@ahmdyasser Maybe something a little more like this...

<img width="411" alt="image" src="https://user-images.githubusercontent.com/806104/198843450-c6bb2588-f756-4a89-8aeb-820cfc40e6f8.png">

**Comment by thecoolwinter** [comment]
This was completed with #174.
