### ISSUE TITLE
✨ Toggle Line Wrap

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#66]
## Acceptance Criteria

- Enable in editor
- Add option to text editing preference pane
- Add command to command palette

**Comment by ben-p-commits** [comment]
Just caught this one... @austincondiff - this can be associated to https://github.com/CodeEditApp/CodeEdit/issues/868 and assigned to me if you'd like. I'll close this out in tandem with that work.

**Comment by ben-p-commits** [comment]
@austincondiff this can be closed!

**Comment by lukepistrol** [comment]
Closed by CodeEditApp/CodeEdit#948
