### ISSUE TITLE
✨ Matching Tag/Bracket Highlighting

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#67]
When the cursor moves to a bracket, the matching bracket temporarily highlights to show the user the opposite bracket.

https://user-images.githubusercontent.com/806104/193524210-a7d6b4f4-9a67-4ad8-9f66-49191eefd5cc.mov

**Comment by thecoolwinter** [comment]
Duplicate of #39, adding the hacktoberfest tag there.

**Comment by austincondiff** [comment]
I'll add an issue description soon
