### ISSUE TITLE
🐞 Clicking empty area where there are no new lines does not clear text selection

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#76]
If I have a file that does not have enough lines to fill the height of my editor, I have empty space below my lines. If I made a selection and then clicked this empty area, I would expect for the selection to be cleared and that the cursor would be moved to the end of the file. Instead, it does nothing as shown...

https://user-images.githubusercontent.com/806104/193937199-af76f539-f104-41e6-bc3c-4fc9235dea4b.mov

**Comment by lukepistrol** [comment]
Related to #56

**Comment by austincondiff** [comment]
Will be complete with
- #56 
- #145
