### ISSUE TITLE
✨ Matching tag and bracket pairs

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#79]
When user types a `{`, `[`, `(`, or `<`, we should append a matching `}`, `]`, `)`, or `>` right after the cursor position on the same line.

## Related
- #78

**Comment by mattmassicotte** [comment]
This one of the core features of this library: https://github.com/ChimeHQ/TextFormation

Might be handy. It is text-system independent, so should be possible to incorporate into any system. But, does have some more straightforward hooks for NSTextView.

**Comment by lukepistrol** [comment]
Could be implemented using https://github.com/ChimeHQ/TextFormation
