### ISSUE TITLE
🐞 Respect Users Tab Width setting

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#80]
We need to respect the users Tab Width setting from the CodeEdit main app.

**Comment by lukepistrol** [comment]
Could be implemented using https://github.com/ChimeHQ/TextFormation

**Comment by thecoolwinter** [comment]
No there's a draft PR for this open. Needs clarification on what settings to support.

**Comment by thecoolwinter** [comment]
There are two settings that need to be supported and #147 only fixes one:
- Tab width: The visual space a tab character takes on the screen, usually measured in "number of spaces"
- Indent behavior: What to insert on a tab key press. This can be either spaces (with a count) or tabs, which is what #147 adds.
