### ISSUE TITLE
🐞 Text doesn't re-wrap on width change

### ISSUE THREAD

**Issue by thecoolwinter** [CodeEditApp/CodeEditTextView#84]
# Description

When changing the width of the view the text won't unwrap or wrap lines as the width changes. However, if you scroll away from the text and scroll back to it, it is laid out correctly.

This might just require forcing a layout when the view's width changes.

# To reproduce

- Open a file with a long line of text
- Change the width of the screen so that the long line should either wrap more or unwrap
- Scroll away so the text is no longer visible
- Scroll back up to the original line (it should now be wrapped correctly according to the new width)

# Expected Behavior

The lines should update as the view width changes, instead of needing a scroll to re-layout.

# Additional Context

https://user-images.githubusercontent.com/35942988/198495074-e7c43f4d-48c3-4e21-8297-cf8ee66de283.mov

# Relate Issues

- CodeEditApp/CodeEdit#868

This issue should be worked on with the above issue.

**Comment by ben-p-commits** [comment]
@thecoolwinter - can you assign this one to me? knocking it out in tandem with https://github.com/CodeEditApp/CodeEditTextView/issues/66, and https://github.com/CodeEditApp/CodeEdit/issues/868.

**Comment by thecoolwinter** [comment]
> @thecoolwinter - can you assign this one to me? knocking it out in tandem with https://github.com/CodeEditApp/CodeEditTextView/issues/66, and https://github.com/CodeEditApp/CodeEdit/issues/868.

For sure! Make sure to mention the issues in any PRs you make too.

**Comment by thecoolwinter** [comment]
Fixed with #105. Thanks Ben!
